# Site settings

url: "http://kistar2010.github.io"
title: "{ Racquel Ivy Awuor }"
description: "Blog and website of Ivy Awuor"
keywords: "panos, sakkos, panos sakkos, technology, computer science, Pwn Mail, WriteRight, UoA, di, CERN, MDCN, Microsoft"
#keywords:"racquel, awuor, ivy, rawuor, technology, computer science, electrical engineering, computer engineering, research, programming"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-35880426-3"
#google-tracking-id:false
disqus-shortname: "rawuor"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  #Blog: 'blog'
  #Research:'research'
  Projects: 'projects'
  Career: 'career'
  Contact: 'contact'

#background-img: "/img/intro-bg.jpg"
background-img: "/img/intro-bg1.jpg"

# About variables

me-img: "/img/me1.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: False

projects:
  - title: "Flappy bird clone"
    description: "Used XCode and SpriteKit to create a clone of the Flappy bird game for iOS. Code on github: <a href = \"https://github.com/rawuor\" target =\"_blank\">Here!</a>"

# Career variables

events:
  - image: "/img/career/microsoft.jpg"
    date: "September 2014 - Today"
    description: "Software Engineer @ Microsoft Development Center Norway, working @ the <a href=\"http://dev.office.com/officegraph\" target=\"_blank\"> Office Graph</a>"
  - image: "/img/career/uoa.jpg"
    date: "October 2012 - August 2014"
    description: "Master studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Software Engineering + <a href=\"http://scholar.google.com/citations?user=UtV6LFYAAAAJ&amp;hl=en&amp;oi=ao\" target=\"_blank\">Machine Learning researcher</a> @ <a href=\"http://kddlab.di.uoa.gr\" target=\"_blank\">KDD</a> lab"
  - image: "/img/career/cern.jpg"
    date: "October 2011 - September 2012"
    description: "Security researcher @ <a href=\"http://www.cern.ch\" target=\"_blank\">CERN</a>, developed linux kernel extensions to prevent cyber attacks"
  - image: "/img/career/writeright.jpg"
    date: "August 2011 - Today"
    description: "Released <a href=\"https://play.google.com/store/apps/details?id=panos.sakkos.softkeyboard.writeright\" target=\"_blank\">WriteRight</a>, an adaptive S/W keyboard for Android devices, which  shrinks the unlikely keys to tap next. Currently it holds &gt; 9,000 downloads"
  - image: "/img/career/pwnmail.jpg"
    date: "June 2010 - November 2010"
    description: "Released <a href=\"https://www.google.com/search?q=pwn+mail\" target=\"_blank\">Pwn Mail</a>, an iPhone app for spoofing emails. It served &gt; 260,000 emails but it was discontinued after a legal threat by <strike>Steve Jobs</strike> a secretary of Steve Jobs"
  - image: "/img/career/uoa.jpg"
    date: "October 2007 - September 2011"
    description: "Bachelor studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Computer Science and Telecomunications"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/rawuor"
  - title: "linkedin"
    #url: "http://no.linkedin.com/in/PanosSakkos"
    url: "https://www.linkedin.com/pub/ivy-awuor/5a/3ba/2ab"
  - title: "facebook"
    url: "https://www.facebook.com/iracquel1"
    #url:"https://www.youtube.com/channel/UCO7m8lbIOD2aAm5z3hS8l7g"
  - title: "quora"
    #url: "https://soundcloud.com/psakkos/"
    url: "https://www.quora.com/Ivy-Racquel"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
